version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - maintidx
    - gocritic
    - unparam
    - spancheck
    - nestif
    - iface
    - paralleltest
    - gocognit
    - exhaustive
    - interfacebloat
    - unconvert
    - gochecknoglobals
    - err113
    - wrapcheck
    - nilerr
    - mnd
    - zerologlint
    - bodyclose
    - tagalign
    - importas
    - goprintffuncname
    - nosprintfhostport
    - noinlineerr
    - mirror
    - modernize
    - ineffassign
    - errorlint
    - fatcontext
    - unqueryvet
    - embeddedstructfieldcheck
    - intrange
    - ireturn
    - forbidigo
    - errname
    - noctx
    - recvcheck
    - inamedparam
    - funcorder
    - gochecknoinits
    - funlen
    - tparallel
    - wastedassign
    - nlreturn
    - goconst
    - cyclop
    - copyloopvar
    - testifylint
    - sqlclosecheck
    - varnamelen
    - goheader
    - wsl_v5
    - staticcheck
    - forcetypeassert
    - gosec
    - usestdlibvars
    - loggercheck
    - errchkjson
    - gosmopolitan
    - godoclint
    - govet
    - asasalint
    - promlinter
    - protogetter
    - exptostd
    - canonicalheader
    - revive
    - depguard
    - unused
    - dogsled
    - nilnil
    - bidichk
    - asciicheck
    - decorder
    - dupword
    - testableexamples
    - iotamixing
    - nakedret
    - gocheckcompilerdirectives
    - contextcheck
    - godox
    - nonamedreturns
    - ginkgolinter
    - tagliatelle
    - musttag
    - testpackage
    - prealloc
    - predeclared
    - nilnesserr
    - nolintlint
    - reassign
    - containedctx
    - rowserrcheck
    - exhaustruct
    - whitespace
    - gochecksumtype
    - sloglint
    - dupl
    - grouper
    - godot
    - makezero
    - thelper
    - usetesting
    - gomoddirectives
    - arangolint
    - gocyclo
    - gomodguard
    - durationcheck
    - misspell
    - perfsprint
    - errcheck
formatters:
  enable:
    - golines
issues: {}
