version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - revive
    - noctx
    - contextcheck
    - gomoddirectives
    - godox
    - inamedparam
    - forbidigo
    - unconvert
    - ineffassign
    - makezero
    - ireturn
    - nakedret
    - goprintffuncname
    - unqueryvet
    - thelper
    - durationcheck
    - nolintlint
    - loggercheck
    - funcorder
    - prealloc
    - tagliatelle
    - zerologlint
    - maintidx
    - nosprintfhostport
    - iface
    - goconst
    - godoclint
    - modernize
    - spancheck
    - rowserrcheck
    - mnd
    - interfacebloat
    - testableexamples
    - protogetter
    - usestdlibvars
    - containedctx
    - promlinter
    - bidichk
    - gochecksumtype
    - ginkgolinter
    - wrapcheck
    - nonamedreturns
    - sloglint
    - exhaustive
    - testifylint
    - embeddedstructfieldcheck
    - intrange
    - grouper
    - mirror
    - cyclop
    - unused
    - fatcontext
    - bodyclose
    - errorlint
    - gocyclo
    - canonicalheader
    - gomodguard
    - misspell
    - varnamelen
    - gochecknoglobals
    - gocognit
    - usetesting
    - nilerr
    - importas
    - govet
    - funlen
    - gochecknoinits
    - recvcheck
    - nilnesserr
    - nestif
    - dupl
    - godot
    - testpackage
    - whitespace
    - decorder
    - perfsprint
    - copyloopvar
    - sqlclosecheck
    - unparam
    - lll
    - tagalign
    - wastedassign
    - errcheck
    - asasalint
    - dupword
    - staticcheck
    - tparallel
    - gosec
    - gocritic
issues: {}
